# latihan 1

In [1]:
import numpy as np

arr = np.array([1,2,7,6,5,4,3,8])
print(arr)

print(np.append(arr,[1,2]))

print(np.delete(arr,1))

print(np.sort(arr))

[1 2 7 6 5 4 3 8]
[1 2 7 6 5 4 3 8 1 2]
[1 7 6 5 4 3 8]
[1 2 3 4 5 6 7 8]


# latihan 2

In [3]:
import numpy as np

ex = np.array([[[1,2,3,4],
                [5,6,7,8]],

                [[9,10,11,12],
                [13,14,15,16]],

                [[17,18,19,20],
                [21,22,23,24]]])
print(ex)

print(ex.ndim)
print(ex.size)
print(ex.shape)



[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
3
24
(3, 2, 4)


# latihan 3

In [4]:
import numpy as np
ex = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

print(ex)

print(ex.reshape(3,2,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


# latihan 4

In [5]:
import numpy as np
ex = np.array([1,2,3,4,5,6,7,8,9,10])

ex2 = np.expand_dims(ex, axis=1)
print(ex2.shape)

ex3 = np.expand_dims(ex, axis=0)
print(ex3.shape)

ex4 = ex[np.newaxis]
print(ex4.shape)

ex5 = ex[:, np.newaxis]
print(ex5.shape)



(10, 1)
(1, 10)
(1, 10)
(10, 1)


# latihan 5

In [6]:
import numpy as np
a1 = np.array([[11,12,13,14], [15,16,17,18], [19,20,21,22], [23,24,25,26], [27,28,29,30]])

print(a1)
print(a1[a1>=13])
a2 = (a1>=10)
print(a1[a2])
print(a1[a1%2==1])
print(a1[a1%2==0])

a3 = np.array([1,2,3,4,5,6,7,8,9,10])
aa = a3[5:7]
print(aa)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]
[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[11 13 15 17 19 21 23 25 27 29]
[12 14 16 18 20 22 24 26 28 30]
[6 7]


# latihan 6

In [7]:
import numpy as np
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print(a1)
print(a2)

print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

x1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
x2 = np.hsplit(x1,4)
x3 = x1.view()
x4 = x1.copy()
print(x1)
print(x2)
print(x3)
print(x4)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12]), array([13, 14, 15, 16, 17, 18]), array([19, 20, 21, 22, 23, 24])]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
